name: Build ESPHome firmware

on:
  workflow_dispatch:
    inputs:
      yaml_file:
        description: 'Config file'
        required: true
        default: 'xiaozhi-skr.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ESPHome
        uses: esphome/esphome-action@v1
        with:
          yaml_file: ${{ inputs.yaml_file }}
