name: Build ESPHome firmware
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install ESPHome
        run: |
          python -m pip install --upgrade pip
          pip install esphome
      
      - name: List files to debug
        run: ls -la
      
      - name: Compile all yaml files
        run: esphome compile *.yaml
      
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .esphome/build/*/firmware.bin
